version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  cache:
    image: redis

  bundle:
    image: busybox
    volumes:
      - /usr/local/bundle

  web:
    build: .
    command:
      [ "bash", "-c", "bundle check || bundle install; rm -f tmp/pids/server.pid; rails server -p 3000 -b 0.0.0.0" ]
    volumes:
      - .:/usr/src/myapp
    volumes_from:
      - bundle
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_HOST=db
      - CACHE_HOST="redis://cache:6379/0"
      - DEBUG_WITH_SPRING=true
    depends_on:
      - bundle
    links:
      - db
      - cache
